/*
** Please edit this file as needed **
It's been generated by Zapatos as a custom type definition placeholder, and won't be overwritten
*/


declare module 'zapatos/custom' {
  import type * as db from 'zapatos/db';

  interface Option {
    id : string
    max : number
    min : number
    name : string
    price : number
    description : string
  }

  interface Attribute {
    type : "sizes" | "additionals"
    options : Array<Option>
  }

  export type PgAttributes = Array<Attribute>;  // replace with your custom type or interface as desired
}

